---
- name: Initiate server configuration
  hosts: all
  become: yes
  gather_facts: yes
  remote_user: "{{ ansible_user }}"
  vars:
      ansible_become_pass: "{{ lookup('ansible.builtin.env', 'SERVER_03100_SUDO_PASS') }}"
      ansible_ssh_host_key_checking: false
  tasks:
      - name: 1/11 - Update and upgrade apt packages
        ansible.builtin.apt:
            update_cache: yes
            upgrade: yes

      - name: 2/11 - Install apt dependencies
        ansible.builtin.apt:
            name: "{{ item  }}"
            state: present
            update_cache: true
        loop:
          - apt-transport-https
          - build-essential
          - ca-certificates
          - curl
          - dkms
          - dpkg-dev
          - gcc
          - gcc-multilib
          - git
          - gnupg
          - gnupg-agent
          - libc-dev
          - libglvnd-dev
          - libgtk-3-0
          - make
          - pkg-config
          - python3-setuptools
          - snapd
          - software-properties-common
          - wget

      - name: 3/11 - Download Micro using curl
        ansible.builtin.get_url:
            url: https://getmic.ro
            dest: /tmp/getmicro.sh
            mode: "0755"

      - name: 4/11 - Execute Micro install script
        ansible.builtin.shell:
            cmd: /tmp/getmicro.sh
            creates: /usr/bin/micro

      - name: 5/11 - Move Micro to /usr/bin/micro
        ansible.builtin.command:
            cmd: mv micro /usr/bin/micro
            creates: /usr/bin/micro

      - name: 8/11 - Include SSHD configuration variables
        include_vars: ../vars/security.yml

      - name: 9/11 - Configure SSHD
        ansible.builtin.include_role:
            name: geerlingguy.security

      - name: 10/11 - Configure server to never sleep
        ansible.builtin.include_role:
            name: l3d.no_sleep