apiVersion: v1
kind: Secret
metadata:
  name: scraped-consumer-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "your_client_db_password"
  POSTGRES_USER: "your_client_db_user"
  POSTGRES_DB: "your_client_db_name"
