apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-db
spec:
  selector:
    matchLabels:
      app: airflow-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: airflow-db-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: airflow-db-pvc
