apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: airflow-triggerer
  template:
    metadata:
      labels:
        component: airflow-triggerer
    spec:
      containers:
      - name: airflow-triggerer
        image: epitechuser2077/cryptodata:cryptodata-airflow
        command: ["airflow", "triggerer"]
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
        - name: logs-volume
          mountPath: /opt/airflow/logs
        - name: config-volume
          mountPath: /opt/airflow/config
        - name: plugins-volume
          mountPath: /opt/airflow/plugins
        readinessProbe:
          exec:
            command: ["sh", "-c", "airflow jobs check --job-type TriggererJob --hostname \"$(hostname)\""]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
      volumes:
      - name: dags-volume
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: config-volume
        persistentVolumeClaim:
          claimName: airflow-config-pvc
      - name: plugins-volume
        persistentVolumeClaim:
          claimName: airflow-plugins-pvc
