apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraped-consumer
spec:
  selector:
    matchLabels:
      app: scraped-consumer
  template:
    metadata:
      labels:
        app: scraped-consumer
    spec:
      containers:
      - name: scraped-consumer
        image: epitechuser2077/cryptodata:cryptodata-scraped_consumer
        command: ["python", "main.py"]
        envFrom:
        - secretRef:
            name: scraped-consumer-secrets
        volumeMounts:
        - name: consumer-data
          mountPath: /home/consumer
      volumes:
      - name: consumer-data
        persistentVolumeClaim:
          claimName: scraped-consumer-pvc
