apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-cli-job
spec:
  template:
    spec:
      containers:
      - name: airflow-cli
        image: epitechuser2077/cryptodata:cryptodata-airflow
        command: ["bash", "-c", "airflow"]
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
      restartPolicy: OnFailure