apiVersion: batch/v1
kind: Job
metadata:
  name: client-initdb
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: epitechuser2077/cryptodata:cryptodata-client_initdb
        command: ["python3", "/srv/app/initdb.py"]
        volumeMounts:
        - mountPath: /srv/app
          name: init-script-volume
      restartPolicy: OnFailure
      volumes:
      - name: init-script-volume
        configMap:
          name: initdb-script
