version: '2'

services:
    kafka_monitor:
        build:
            context: .
            dockerfile: docker/kafka-monitor/Dockerfile.py3
        depends_on:
            - kafka
            - redis
        restart: always

    redis_monitor:
        build:
            context: .
            dockerfile: docker/redis-monitor/Dockerfile.py3
        depends_on:
            - kafka
            - redis
            - zookeeper
        restart: always

    crawler:
        build:
            context: .
            dockerfile: docker/crawler/Dockerfile.py3
        depends_on:
            - kafka
            - redis
            - zookeeper
        restart: always

    rest:
        build:
            context: .
            dockerfile: docker/rest/Dockerfile.py3
        depends_on:
            - kafka
            - redis
        restart: always
        ports:
            - '5343:5343'

    redis:
        image: redis
        ports:
            - '6379:6379'
        restart: always

    zookeeper:
        image: zookeeper:3.9.0
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
        ports:
            - '2181:2181'
            - '8081:8081'
        restart: always
        volumes:
            - ./utils/config/zoo.cfg:/conf/zoo.cfg
            - zookeeper_data:/data
            - zookeeper_datalog:/datalog

    kafka:
        image: wurstmeister/kafka
        ports:
            - '9092:9092'
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_ADVERTISED_HOST_NAME: kafka
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper
        restart: always

volumes:
    zookeeper_data:
        driver: local
    zookeeper_datalog:
        driver: local
